---
title: "Report"
date: "2024-03-21"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 3
  header-includes:
    -\usepackage{fancyhdr}
    -\usepackage{lipsum}
    -\pagestyle{fancy}
    -\fancyhead[R]{\thepage}
    -\fancypagestyle{plain}{\pagestyle{fancy}}
---
```{r setup}
knitr::opts_chunk$set(
  collapse = TRUE, 
  warning = FALSE, 
  message = FALSE,
  fig.dim = c(10, 5),
  fig.format = "png")
```

# Load Data and Package

```{r}
library(tidyverse)
library(caret)
## Load the the training/test set & control method

# Load the training and test sets
train_data <- read.csv("./Data/train_data.csv")
test_data <- read.csv("./Data/test_data.csv")

# Load the control method
ctrl1 <- readRDS("./Data/train_control.rds")

# change variables to be factors again
train_data <- train_data %>%
  mutate(gender = as_factor(gender),
         diabetes = as_factor(diabetes),
         hypertension = as_factor(hypertension),
         vaccine = as_factor(vaccine),
         severity = as_factor(severity))

test_data <- test_data %>%
  mutate(gender = as_factor(gender),
         diabetes = as_factor(diabetes),
         hypertension = as_factor(hypertension),
         vaccine = as_factor(vaccine),
         severity = as_factor(severity))
```

# GAM

```{r}
set.seed(1)

x_train = train_data[1:14]
y_train = train_data$recovery_time

x_test = test_data[1:14]
y_test = test_data$recovery_time

model.gam <- train(x = x_train,
                   y = y_train,
                   method = "gam",
                   #metric = "RMSE", by default
                   trControl = trainControl(method = "cv", number = 10))


model.gam$finalModel

#plot(model.gam$finalModel)

# Calculate training RMSE of optimal model
gam_train_RMSE = sqrt(mean((y_train - predict(model.gam))^2))
gam_train_RMSE

# Calculate test RMSE of optimal model
test_predictions = predict(model.gam, x_test)

gam_test_RMSE = sqrt(mean((y_test - test_predictions)^2))
gam_test_RMSE

# 预测值
predictions <- predict(gam_model, newdata = train_data)

# 计算总偏差（Total Sum of Squares）
TSS <- sum((train_data$recovery_time - mean(train_data$recovery_time))^2)

# 计算残差偏差（Residual Sum of Squares）
RSS <- sum((train_data$recovery_time - predict(model.gam))^2)

# 计算R²
R2 <- 1 - (RSS/TSS)
R2

```

## MARS

```{r}

# matrix of predictors 
x <- model.matrix(recovery_time ~ ., dat |> select(-id))[, -1]
# vector of response
y <- dat$recovery_time

mars_grid <- expand.grid(degree = 1:3, 
                         nprune = 2:15)

set.seed(2)
ctrl1 <- trainControl(method = "cv", number = 10)

mars.fit <- train(x, y,
                  method = "earth",
                  tuneGrid = mars_grid,
                  trControl = ctrl1)


ggplot(mars.fit)


mars.fit$bestTune

coef(mars.fit$finalModel) 
```

